name: deploy

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '16.x'
            - name: Build web-app
              run: |
                  yarn install
                  yarn run build
              env:
                  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
                  REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }}
            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
